import open3d as o3d
import numpy as np
import cv2
import os


def debug_exact_projection(ply_path):
    print("=== COORD PROJECTION RADAR DETECTOR ===")
    if not os.path.exists(ply_path):
        print(f"[ERROR] Missing file: {ply_path}")
        return

    # 1. Load the exact geometry data from your capture
    pcd = o3d.io.read_point_cloud(ply_path)
    print(f"[DATA] Loaded point cloud containing {len(pcd.points)} points.")

    # 2. Extract the Floor to find the outliers
    plane_model, inliers = pcd.segment_plane(
        distance_threshold=0.01, ransac_n=3, num_iterations=1000
    )
    outlier_cloud = pcd.select_by_index(inliers, invert=True)

    # 3. Cluster using DBSCAN to isolate the physical target block
    labels = np.array(
        outlier_cloud.cluster_dbscan(eps=0.015, min_points=8, print_progress=False)
    )
    if labels.size == 0 or not np.any(labels >= 0):
        print("[ERROR] No dense object structures found in point cloud data.")
        return

    unique_labels, counts = np.unique(labels[labels >= 0], return_counts=True)
    largest_cluster_idx = unique_labels[np.argmax(counts)]
    box_cloud = outlier_cloud.select_by_index(
        list(np.where(labels == largest_cluster_idx)[0])
    )

    print(f"[SUCCESS] Isolated target cluster with {len(box_cloud.points)} points.")

    # 4. Your explicit physical camera intrinsics (pulled directly from your Orbbec setup profile)
    # Target frame size matching your cropped window width/height bounds
    w, h = 510, 540

    # We will test the projection against a series of candidate coordinate centers (cx)
    # to find out exactly where the math is placing the object.
    test_canvas = np.zeros((h, w, 3), dtype=np.uint8)

    # Standard camera matrix parameters used by your Open3D workspace
    fx = 461.328
    fy = 461.328

    # Let's print out the raw 3D spatial center of the box to see where it sits relative to the lens
    pts = np.asarray(box_cloud.points)
    mean_x = np.mean(pts[:, 0])
    mean_y = np.mean(pts[:, 1])
    mean_z = np.mean(pts[:, 2])
    print(
        f"\n[GEOMETRY CENTER] Real-world meters from lens center -> X: {mean_x:.3f}m, Y: {mean_y:.3f}m, Z: {mean_z:.3f}m"
    )

    # Let's check where these points land using your current active intrinsic values
    # Option A: Assuming unshifted matrix center
    cx_unshifted = 319.5
    # Option B: Assuming crop-shifted center matrix
    cx_shifted = 319.5 - 250.0  # 69.5

    print("\n--- SIMULATING PROJECTION LOCATIONS ---")

    # Let's see the pixel coordinates generated by both methods
    for cx_val, label in zip(
        [cx_unshifted, cx_shifted],
        ["UNSHIFTED (Normal Lens)", "SHIFTED (Crop Compensated)"],
    ):
        u_coords = []
        v_coords = []
        for x, y, z in pts:
            if z <= 0:
                continue
            u = int((x * fx / z) + cx_val)
            v = int((y * fy / z) + 239.5)  # cy parameter standard
            if 0 <= u < w and 0 <= v < h:
                u_coords.append(u)
                v_coords.append(v)

        if len(u_coords) > 0:
            print(
                f"[{label}] Points landed in frame: {len(u_coords)} pts. Center Pixel column (u) = {int(np.mean(u_coords))}"
            )
        else:
            print(
                f"[{label}] Completely out of window bounds! (All points thrown off-screen)"
            )

    # 5. Generate a diagnostic image showing the true points in Blue and the shifted points in Red
    for x, y, z in pts:
        if z <= 0:
            continue
        # Draw Unshifted in Cyan (Blue/Green)
        u_un = int((x * fx / z) + cx_unshifted)
        v_un = int((y * fy / z) + 239.5)
        if 0 <= u_un < w and 0 <= v_un < h:
            test_canvas[v_un, u_un] = [255, 255, 0]

        # Draw Shifted in Red
        u_sh = int((x * fx / z) + cx_shifted)
        v_sh = int((y * fy / z) + 239.5)
        if 0 <= u_sh < w and 0 <= v_sh < h:
            test_canvas[v_sh, u_sh] = [0, 0, 255]

    output_name = "projection_diagnostic_radar.png"
    cv2.imwrite(output_name, test_canvas)
    print(f"\n[SAVED] Diagnostic tracking map written to: {output_name}")
    print("Please run this script and share the printed console lines text directly.")


if __name__ == "__main__":
    debug_exact_projection("/home/cpsstudent/Documents/ips_s2026/rgbd/dataset/pointcloud/img0937.ply")
